version: "3.8"

services:
  app:
    container_name: app
    build:
      context: .
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - app_data:/var/www/html/web/app/uploads
    ports:
      - 80:80

  db:
    container_name: db
    image: mariadb:11.1.2
    restart: always
    environment:
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_RANDOM_ROOT_PASSWORD: true
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2.1
    restart: unless-stopped
    environment:
      PMA_USER: $DB_USER
      PMA_PASSWORD: $DB_PASSWORD
    depends_on:
      - db
    ports:
      - 8899:80

volumes:
  app_data:
  db_data:
